#----------------------------------------------------------------------------
#
# プラグイン管理
#
[[plugins]]
repo = "Shougo/neosnippet"
hook_add = """
	source ~/dotfiles/toml/conf/neosnippet.vim
"""
[[plugins]]
repo = "Shougo/neosnippet-snippets"
