#----------------------------------------------------------------------------
#
# プラグイン管理
#
[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = """
	source ~/dotfiles/toml/conf/syntastic.vim
"""

